CLOUD-2272 Modify DX Kafka Module
variant-inc/terraform-variant-apps pull request #131
Opened 2023-09-20 15:35 UTC by vibindaniel

# Description

Refactor Kafka Module

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change
(fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration

- [ ] Sanity Testing

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-22 11:45 UTC, zumic96 requested changes

2023-09-22 11:45 UTC, zumic96 commented on modules/apps/ui/pre_run.sh
This is leftover from moving it to scripts folder, same for cron and handler?

2023-09-22 11:45 UTC, zumic96 commented on modules/apps/ui/main.tf
> +            tenantId     = local.auth_secret["aUTH__TenantId"]
Caps lock typo?
Same on API.

2023-09-26 15:25 UTC, vibindaniel commented on modules/common/kafka/outputs.tf
> +    { name = "${replace(local.service_account, local.prefix, "")}-kafka-creds", type = "kafka" },
This is created in the ix-kafka-users-topic repo

2023-09-26 15:25 UTC, vibindaniel commented on modules/apps/ui/pre_run.sh
deleted

2023-09-26 15:25 UTC, vibindaniel commented on modules/apps/ui/main.tf
> +            tenantId     = local.auth_secret["aUTH__TenantId"]
fixed

2023-09-27 07:21 UTC, zumic96 approved these changes

2023-09-27 12:35 UTC, merged